apiVersion: v2
appVersion: 0.0.4
name: policy-meta-operator
description: Policy Meta Operator Helm chart for Giant Swarm
home: https://github.com/giantswarm/policy-meta-operator
icon: https://s.giantswarm.io/app-icons/giantswarm/1/light.svg
version: 0.0.4
annotations:
  application.giantswarm.io/team: shield
  io.giantswarm.application.audience: all
  io.giantswarm.application.managed: "true"
